// Package openapi mounts the gateway's OpenAPI specification and an
// optional Swagger UI viewer.
//
// The specification is generated by `swag init` from the swag annotation
// comments scattered across cmd/gateway and the handler packages. The
// generated artefacts live under services/gateway-go/docs/ and are
// embedded into the binary at compile time so the running gateway can
// always serve the spec that matches its own source — no filesystem
// lookups, no version skew.
//
// Routes (when EnableUI is true):
//
//   - GET /swagger/doc.json       — generated OpenAPI 3.0 document, JSON
//   - GET /swagger/doc.yaml       — generated OpenAPI 3.0 document, YAML
//   - GET /swagger/               — Swagger UI HTML viewer
//   - GET /swagger/swagger-ui.css — UI stylesheet (CDN-pinned via the page)
//
// SECURITY: Swagger UI is gated behind GATEWAY_SWAGGER_UI=true and OFF by
// default. Production deployments serving the spec should expose only
// /swagger/doc.json (consumed by SDK generators) and leave the HTML viewer
// disabled. The viewer itself is read-only — the gateway's REST surface is
// likewise read-only — but a public Swagger UI is a discovery aid for
// attackers and adds nothing for end users.
package openapi

import (
	"errors"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

// Spec carries the in-binary copies of the generated OpenAPI document.
//
// Both forms (json, yaml) are populated from the same swag run so they
// describe the exact same surface; yaml is just the human-readable form.
//
// Construct via NewSpec — the zero value rejects mounting because
// serving an empty spec would mislead SDK consumers into believing the
// API is empty.
type Spec struct {
	JSON []byte
	YAML []byte

	// EnableUI toggles the Swagger UI HTML page. When false, only the raw
	// /swagger/doc.{json,yaml} endpoints are mounted; the UI route itself
	// is absent. This mirrors the GraphQL playground gating in #89.
	EnableUI bool
}

// NewSpec validates the embedded artefacts and returns a ready-to-mount
// Spec. We refuse to mount when the generated bytes are empty so
// shipping a binary that was built without `swag init` having been run
// fails loudly at startup instead of silently.
func NewSpec(jsonDoc, yamlDoc []byte, enableUI bool) (*Spec, error) {
	if len(jsonDoc) == 0 {
		return nil, errors.New("openapi: empty json spec")
	}
	if len(yamlDoc) == 0 {
		return nil, errors.New("openapi: empty yaml spec")
	}
	return &Spec{JSON: jsonDoc, YAML: yamlDoc, EnableUI: enableUI}, nil
}

// Register mounts the spec endpoints (and, when EnableUI is true, the
// Swagger UI viewer) on the supplied router group. The caller chooses
// the prefix; cmd/gateway mounts on the engine root so the canonical
// paths are /swagger/*.
//
// The raw spec endpoints are mounted unconditionally so SDK generators
// that consume the document over HTTP work the same way in production
// (UI off) and dev (UI on). The exact JSON/YAML bytes round-trip — no
// re-marshalling — to keep generated SDKs deterministic across runs.
func (s *Spec) Register(rg *gin.RouterGroup) {
	rg.GET("/swagger/doc.json", s.serveJSON)
	rg.GET("/swagger/doc.yaml", s.serveYAML)
	if s.EnableUI {
		rg.GET("/swagger/", s.serveUI)
		rg.GET("/swagger", s.redirectToTrailing)
	}
}

func (s *Spec) serveJSON(c *gin.Context) {
	c.Header("Content-Type", "application/json; charset=utf-8")
	c.Header("Cache-Control", "no-store")
	_, _ = c.Writer.Write(s.JSON)
}

func (s *Spec) serveYAML(c *gin.Context) {
	// application/yaml is the IANA-registered media type since RFC 9512
	// (2024). It supersedes the long-standing application/x-yaml; we emit
	// the registered form so generators that follow the spec can find the
	// document without having to learn the legacy alias.
	c.Header("Content-Type", "application/yaml; charset=utf-8")
	c.Header("Cache-Control", "no-store")
	_, _ = c.Writer.Write(s.YAML)
}

func (s *Spec) redirectToTrailing(c *gin.Context) {
	// /swagger -> /swagger/ — without the trailing slash the relative URL
	// to doc.json in the embedded HTML resolves at the engine root and the
	// page comes up empty.
	c.Redirect(http.StatusMovedPermanently, "/swagger/")
}

// swaggerUIPage is the Swagger UI viewer HTML. It loads the React
// Swagger UI bundle from a pinned CDN release and points it at the
// in-binary spec served from /swagger/doc.json. We pin a specific
// version so the HTML in this binary cannot break when the upstream
// project ships a new release.
//
// Subresource integrity hashes are intentionally omitted: SRI on a
// fetched script means a CDN-pushed mismatch fails the page closed,
// which would convert a CDN incident into a gateway-level outage of
// the (already off-by-default, dev-only) viewer. The page is served
// only when the operator has explicitly opted in.
const swaggerUIPage = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Titular Gateway API</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css">
  <style>
    html, body { margin: 0; padding: 0; }
    body { background: #fafafa; }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js" crossorigin></script>
  <script>
    window.addEventListener("load", function () {
      window.ui = SwaggerUIBundle({
        url: "/swagger/doc.json",
        dom_id: "#swagger-ui",
        deepLinking: true,
        layout: "BaseLayout",
        // Try-it-out is enabled but most endpoints are read-only; the
        // SIWE/SIWS verify endpoints will fail without a wallet-signed
        // payload, which is the intended behaviour.
        tryItOutEnabled: true,
      });
    });
  </script>
</body>
</html>`

func (s *Spec) serveUI(c *gin.Context) {
	c.Header("Content-Type", "text/html; charset=utf-8")
	c.Header("Cache-Control", "no-store")
	// Strip-only Content-Security-Policy: pinning a CSP for the viewer is
	// future work; the page is dev-only.
	_, _ = c.Writer.Write([]byte(swaggerUIPage))
}

// EnabledFromEnv parses the GATEWAY_SWAGGER_UI knob exactly the same way
// the GraphQL playground gate parses its switch: case-insensitive "true"
// is on, anything else (unset, "false", "0", "FALSE", garbage) is off.
// Centralising the parse here keeps cmd/gateway free of magic strings
// and gives tests a stable hook.
func EnabledFromEnv(raw string) bool {
	return strings.EqualFold(strings.TrimSpace(raw), "true")
}
